all: sequential_implementation student_submission

sequential_implementation: sequential_implementation.cpp
	g++ -Wall -march=native -mavx -o sequential_implementation -O3 sequential_implementation.cpp

student_submission: student_submission.cpp
	g++ -Wall -march=native -mavx -o student_submission -O3 student_submission.cpp
